const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {randomUUID} = require('node:crypto');
const ledger = require('../src/repositories/resourceLedger');
const databaseUrl = process.env.RESOURCE_LEDGER_TEST_DATABASE_URL;
function loadService(mocks, filename = 'ticketServiceTimingService') {
  const target = require.resolve(`../src/services/${filename}`);
  const saved = new Map();
  try {
    for (const [name,exports] of Object.entries(mocks)) {
      const id=require.resolve(path.resolve(path.dirname(target),name));
      saved.set(id,require.cache[id]); require.cache[id]={id,filename:id,loaded:true,exports};
    }
    delete require.cache[target]; return require(target);
  } finally {
    delete require.cache[target];
    for (const [id,original] of saved) { if (original) require.cache[id]=original; else delete require.cache[id]; }
  }
}
test('staff assignment lookup preserves exact scoped identifiers', async () => {
  const ids=['9007199254740993','9007199254740995','9007199254740997'];
  const repo=require('../src/repositories/tenantMembershipLocations');
  assert.equal(await repo.userHasLocationAssignment(...ids,{client:{query:async (_sql,args) => {
    assert.deepEqual(args,ids); return {rows:[{}]};
  }}}),true);
});
test('explicit service sessions under scoped PostgreSQL transaction', {skip:!databaseUrl}, async t => {
  const url=new URL(databaseUrl); assert.equal(url.hostname,'127.0.0.1');
  assert.ok(['/getprio_test','/getprio_ledger_test'].includes(url.pathname));
  const schema=`service_session_${randomUUID().replaceAll('-','')}`;
  const {Pool}=require('pg');
  const pool=new Pool({connectionString:databaseUrl,options:`-c search_path=${schema}`,application_name:schema,max:8});
  const tenant={_id:'1'}; const location={_id:'10'};
  let failEvent=false; let failBooking=false; let failWebhook=false; let failReconciliation=false; let snapshots=0; let pushes=0; let failAllowance=false; let dueRead=0; let dayReads=0; let failPayment=false; let subscriptionUnavailable=false; let paidDeadlineRace=false; let paidDeadlineObserved=false; let verifyPaidUserLock=false;
  const noop=async () => {};
  async function readTicket(id,{client=pool}={}) {
    const r=(await client.query('SELECT * FROM tickets WHERE id=$1',[id])).rows[0];
    return r && {_id:String(r.id),tenantId:String(r.tenant_id),locationId:String(r.location_id),
      status:r.status,joinChannel:r.join_channel,customerConfirmedAt:r.customer_confirmed_at,
      serviceStartedAt:r.service_started_at,serviceEndedAt:r.service_ended_at,serviceOutcome:r.service_outcome,
      userId:r.user_id && String(r.user_id),customerEmail:r.customer_email,customerPhone:r.customer_phone,
      ticketNumber:String(r.id),dateKey:'2026-10-08',lookupCode:r.lookup_code,updatedAt:r.updated_at};
  }
  try {
    await pool.query(`CREATE SCHEMA ${schema};
      CREATE TABLE users(id BIGINT PRIMARY KEY,roles TEXT[],deletion_requested_at TIMESTAMPTZ,platform_access_suspended_at TIMESTAMPTZ,email TEXT,phone TEXT);
      CREATE TABLE tenants(id BIGINT PRIMARY KEY,is_active BOOLEAN,auto_pause_enabled BOOLEAN DEFAULT FALSE,auto_pause_threshold INTEGER,queue_prefix TEXT DEFAULT 'Q');
      CREATE TABLE tenant_memberships(id BIGINT PRIMARY KEY,user_id BIGINT,tenant_id BIGINT,role TEXT,is_active BOOLEAN);
      CREATE TABLE tenant_membership_locations(tenant_membership_id BIGINT,location_id BIGINT);
      CREATE TABLE service_counters(id BIGINT,tenant_id BIGINT,location_id BIGINT,is_active BOOLEAN);
      CREATE TABLE service_counter_assignments(user_id BIGINT,counter_id BIGINT);
      CREATE TABLE store_locations(id BIGINT PRIMARY KEY,tenant_id BIGINT,is_active BOOLEAN,service_timing_enabled BOOLEAN,UNIQUE(id,tenant_id));
      CREATE TABLE location_resource_pools(id BIGINT PRIMARY KEY,tenant_id BIGINT,location_id BIGINT,capacity INTEGER,revision INTEGER,tracking_enabled BOOLEAN,UNIQUE(id,tenant_id,location_id));
      CREATE TABLE service_resource_requirements(tenant_id BIGINT,location_id BIGINT,service_id BIGINT,pool_id BIGINT,units_required INTEGER,revision INTEGER);
      CREATE TABLE bookings(id BIGINT PRIMARY KEY,tenant_id BIGINT,location_id BIGINT,status TEXT,pending_expires_at TIMESTAMPTZ,payment_proof_object_key TEXT,queue_ticket_id BIGINT,fulfillment_outcome_reason TEXT,refund_eligible BOOLEAN,fulfillment_resolved_at TIMESTAMPTZ,updated_at TIMESTAMPTZ,customer_user_id BIGINT,customer_email TEXT,customer_phone TEXT);
      CREATE TABLE booking_bundle_items(id BIGINT PRIMARY KEY,booking_id BIGINT,tenant_id BIGINT,location_id BIGINT,service_id BIGINT,scheduled_start_at TIMESTAMPTZ,scheduled_end_at TIMESTAMPTZ);
      CREATE TABLE tickets(id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,tenant_id BIGINT,location_id BIGINT,status TEXT,join_channel TEXT,customer_confirmed_at TIMESTAMPTZ,
        service_started_at TIMESTAMPTZ,service_started_by_user_id BIGINT,service_ended_at TIMESTAMPTZ,service_ended_by_user_id BIGINT,
        service_outcome TEXT,status_reason TEXT,updated_at TIMESTAMPTZ,served_at TIMESTAMPTZ,unserved_at TIMESTAMPTZ,service_priority_band TEXT,rejoin_deadline_at TIMESTAMPTZ,
        lookup_code TEXT,user_id BIGINT,customer_email TEXT,customer_phone TEXT,UNIQUE(id,tenant_id,location_id));
      CREATE TABLE ticket_service_plans(ticket_id BIGINT PRIMARY KEY,tenant_id BIGINT,location_id BIGINT,source TEXT,booking_id BIGINT,items JSONB);
      CREATE TABLE events(id BIGSERIAL PRIMARY KEY,ticket_id BIGINT,event_type TEXT,metadata JSONB,actor_role TEXT);
      CREATE TABLE webhooks(event_id BIGINT);
      CREATE TABLE queue_ticket_segments(ticket_id BIGINT,ended_at TIMESTAMPTZ,segment_outcome TEXT,outcome_reason TEXT,queue_day_id BIGINT,display_number TEXT,sequence INTEGER,priority_band TEXT,UNIQUE(ticket_id,queue_day_id));
      CREATE TABLE queue_day_state(state TEXT,closes_at TIMESTAMPTZ DEFAULT clock_timestamp()-interval '1 second',intake_mode TEXT DEFAULT 'accepting',next_sequence INTEGER DEFAULT 1);
      CREATE TABLE intake_state(paused BOOLEAN);
      CREATE TABLE lifecycle_notifications(ticket_id BIGINT,status TEXT);
      CREATE TABLE booking_audit(ticket_id BIGINT,metadata JSONB);
      CREATE TABLE counters(tenant_id BIGINT,location_id BIGINT,key TEXT,date_key TEXT,value INTEGER,PRIMARY KEY(tenant_id,location_id,key,date_key));
      CREATE TABLE vendor_services(id BIGINT PRIMARY KEY,tenant_id BIGINT,name TEXT,duration_minutes INTEGER,is_active BOOLEAN);
      CREATE TABLE location_services(service_id BIGINT,tenant_id BIGINT,location_id BIGINT,is_active BOOLEAN);
      CREATE TABLE store_hours(id BIGSERIAL PRIMARY KEY,location_id BIGINT,weekday INTEGER,opens_at TIME,closes_at TIME,is_closed BOOLEAN,created_at TIMESTAMPTZ,updated_at TIMESTAMPTZ);
      CREATE TABLE allowance_audit(ticket_id BIGINT,resource_key TEXT);
      CREATE TABLE queue_email_journeys(id BIGSERIAL PRIMARY KEY,tenant_id BIGINT,ticket_id BIGINT UNIQUE,mode TEXT,otp_chain_id TEXT,email_opted_out_at TIMESTAMPTZ);
      CREATE TABLE queue_email_slots(journey_id BIGINT,slot_key TEXT,status TEXT DEFAULT 'unused',logical_message_key TEXT,sent_at TIMESTAMPTZ,UNIQUE(journey_id,slot_key));
      CREATE TABLE queue_join_payments(id BIGINT PRIMARY KEY,tenant_id BIGINT,otp_id BIGINT,plan_slug TEXT DEFAULT 'free',provider TEXT DEFAULT 'paymongo',
        provider_checkout_session_id TEXT,provider_payment_id TEXT,status TEXT DEFAULT 'pending',amount_cents INTEGER DEFAULT 100,currency TEXT DEFAULT 'PHP',checkout_url TEXT,
        payload JSONB DEFAULT '{}',metadata JSONB DEFAULT '{}',ticket_id BIGINT,ticket_lookup_code TEXT,queue_day_id BIGINT,queue_day_version_at_checkout INTEGER,
        ticket_issuance_status TEXT DEFAULT 'pending',ticket_issuance_reason TEXT,ticket_issuance_attempted_at TIMESTAMPTZ,paid_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT clock_timestamp(),updated_at TIMESTAMPTZ);
      CREATE TABLE payment_allowance(reservation_key TEXT PRIMARY KEY,state TEXT,ticket_id BIGINT);
      ALTER TABLE store_locations ADD COLUMN slug TEXT DEFAULT 'main';
      ALTER TABLE location_resource_pools ADD COLUMN name TEXT DEFAULT 'Court';
      ALTER TABLE ticket_service_plans ADD COLUMN execution_mode TEXT, ADD COLUMN created_by_user_id BIGINT;
      ALTER TABLE users ADD COLUMN display_name TEXT;
      ALTER TABLE store_locations ADD COLUMN queue_lifecycle_mode TEXT DEFAULT 'legacy', ADD COLUMN timezone TEXT DEFAULT 'Asia/Manila';
      ALTER TABLE bookings ADD COLUMN reference TEXT DEFAULT 'BK-1', ADD COLUMN scheduled_start_at TIMESTAMPTZ,
        ADD COLUMN scheduled_end_at TIMESTAMPTZ, ADD COLUMN execution_mode TEXT DEFAULT 'single';
      ALTER TABLE booking_bundle_items ADD COLUMN sort_order INTEGER DEFAULT 0;
      ALTER TABLE tickets ADD COLUMN service_counter_id BIGINT, ADD COLUMN ticket_number TEXT,
        ADD COLUMN sequence INTEGER, ADD COLUMN date_key TEXT DEFAULT '20261008', ADD COLUMN queue_date_key TEXT,
        ADD COLUMN developer_project_id BIGINT, ADD COLUMN developer_environment TEXT, ADD COLUMN external_reference TEXT,
        ADD COLUMN customer_name TEXT, ADD COLUMN notify_by_email BOOLEAN DEFAULT FALSE, ADD COLUMN notify_by_sms BOOLEAN DEFAULT FALSE,
        ADD COLUMN notes TEXT, ADD COLUMN notified_almost_there_at TIMESTAMPTZ, ADD COLUMN notified_called_at TIMESTAMPTZ,
        ADD COLUMN called_at TIMESTAMPTZ, ADD COLUMN skipped_at TIMESTAMPTZ, ADD COLUMN cancelled_at TIMESTAMPTZ,
        ADD COLUMN carried_over_at TIMESTAMPTZ, ADD COLUMN carry_over_count INTEGER DEFAULT 0,
        ADD COLUMN original_queue_day_id BIGINT, ADD COLUMN current_queue_day_id BIGINT,
        ADD COLUMN pending_carry_over_since TIMESTAMPTZ, ADD COLUMN carry_over_expires_at TIMESTAMPTZ,
        ADD COLUMN carry_over_consumed BOOLEAN DEFAULT FALSE, ADD COLUMN terminal_at TIMESTAMPTZ,
        ADD COLUMN replacement_for_ticket_id BIGINT, ADD COLUMN email_journey_mode TEXT,
        ADD COLUMN created_at TIMESTAMPTZ DEFAULT clock_timestamp()`);
    await pool.query(fs.readFileSync(path.resolve(__dirname,'../../database/migrations/20261007_add_resource_ledger_foundation.sql'),'utf8'));
    const mocks={
      '../config/db':{pool},
      '../repositories/tickets':{findTicketById:readTicket,findTicketByIdForUpdate:async (id,{client}) => {
        await client.query('SELECT id FROM tickets WHERE id=$1 FOR UPDATE',[id]); return readTicket(id,{client});
      }},
      '../repositories/bookings':{updateBookingByQueueTicketId:async (id,data,{client}) => {
        await client.query('UPDATE bookings SET status=$2 WHERE queue_ticket_id=$1',[id,data.status]);
        await client.query('INSERT INTO booking_audit VALUES($1,$2)',[id,JSON.stringify(data)]);
        if (failBooking) throw new Error('booking failed');
      }},
      '../repositories/queueEvents':{createQueueEvent:async (data,{client}) => {
        const r=await client.query('INSERT INTO events(ticket_id,event_type,metadata,actor_role) VALUES($1,$2,$3,$4) RETURNING id',[data.ticketId,data.eventType,JSON.stringify(data.metadata),data.actorRole]);
        if (verifyPaidUserLock && data.eventType==='ticket_created') await assert.rejects(pool.query('SELECT id FROM users WHERE id=1 FOR UPDATE NOWAIT'),{code:'55P03'});
        if (failEvent) throw new Error('event failed'); return {_id:String(r.rows[0].id)};
      }},
      './developerWebhookService':{enqueueQueueEvent:async ({event},{client}) => {
        await client.query('INSERT INTO webhooks VALUES($1)',[event._id]);
        if (failWebhook) throw new Error('webhook failed');
      }},
      './queueService':{publishSnapshot:async () => {snapshots++; return {}; }},
      './queueAutomationHelpers':{maybeAutoResumeQueueDay:noop,maybeAutoPauseQueueDay:noop,maybeNotifyUpcomingTickets:noop},
      './notificationService':{notifyJourneyLifecycle:noop},
      './pushNotificationService':{notifyCustomerQueueUpdate:async () => {pushes++; }}
    };
    const service=loadService(mocks);
    const record=(id,action,actor='1',selected=location) => service.recordTicketService(tenant,id,action,{location:selected,actorUserId:actor});
    async function reset(capacity=4,enabled=true) {
      await pool.query(`TRUNCATE resource_ledger_commands,resource_allocations,resource_ledger_reservations,resource_ledger_scopes,
        ticket_service_plans,tickets,booking_bundle_items,bookings,service_resource_requirements,location_resource_pools,
        store_locations,tenant_membership_locations,service_counter_assignments,service_counters,tenant_memberships,tenants,users,events,webhooks,booking_audit,queue_ticket_segments,queue_day_state,intake_state,lifecycle_notifications,counters,vendor_services,location_services,store_hours,allowance_audit,queue_email_slots,queue_email_journeys,queue_join_payments,payment_allowance RESTART IDENTITY CASCADE`);
      await pool.query(`INSERT INTO users(id,roles,deletion_requested_at,platform_access_suspended_at,email,phone) VALUES(1,'{}',NULL,NULL,'owner@example.com','09171234567'),(2,'{}',NULL,NULL,'other@example.com','09179876543');
        INSERT INTO tenants(id,is_active) VALUES(1,TRUE),(2,TRUE);
        INSERT INTO tenant_memberships VALUES(1,1,1,'owner',TRUE),(2,2,1,'staff',TRUE);
        INSERT INTO store_locations(id,tenant_id,is_active,service_timing_enabled) VALUES(10,1,TRUE,TRUE),(20,2,TRUE,TRUE);
        INSERT INTO service_resource_requirements VALUES(1,10,1000,100,1,1);
        INSERT INTO queue_day_state(state) VALUES('open'); INSERT INTO intake_state VALUES(FALSE);
        INSERT INTO vendor_services VALUES(1000,1,'Court play',60,TRUE); INSERT INTO location_services VALUES(1000,1,10,TRUE);
        INSERT INTO store_hours(location_id,weekday,opens_at,closes_at,is_closed) SELECT 10,n,'00:00','00:00',FALSE FROM generate_series(0,6) n`);
      await pool.query('INSERT INTO location_resource_pools(id,tenant_id,location_id,capacity,revision,tracking_enabled) VALUES(100,1,10,$1,1,$2)',[capacity,enabled]);
      failEvent=false; failBooking=false; failWebhook=false; failReconciliation=false; snapshots=0; pushes=0; failAllowance=false; dueRead=0; dayReads=0; failPayment=false; subscriptionUnavailable=false; paidDeadlineRace=false; paidDeadlineObserved=false; verifyPaidUserLock=false; queueClosed=false;
      delete location.queueLifecycleMode;
    }
    async function ticket(id,{plan=true,booking=false,channel='vendor'}={}) {
      await pool.query("INSERT INTO tickets(id,tenant_id,location_id,status,join_channel,lookup_code,customer_email,customer_phone) VALUES($1,1,10,'called',$2,$3,'owner@example.com','09171234567')",[id,channel,`LOOKUP-${id}`]);
      const item={serviceId:'1000',durationMinutes:60,resource:{known:true,poolId:'100',poolRevision:1,requirementRevision:1,unitsRequired:1}};
      if (booking) {
        const epoch=Date.now()-60000; const start=new Date(epoch).toISOString(); const end=new Date(epoch+3600000).toISOString();
        await pool.query("INSERT INTO bookings(id,tenant_id,location_id,status,pending_expires_at,payment_proof_object_key,queue_ticket_id,customer_email,customer_phone,scheduled_start_at,scheduled_end_at) VALUES(1,1,10,'confirmed',NULL,NULL,$1,'owner@example.com','09171234567',$2,$3)",[id,start,end]);
        await pool.query('INSERT INTO booking_bundle_items(id,booking_id,tenant_id,location_id,service_id,scheduled_start_at,scheduled_end_at) VALUES(1,1,1,10,1000,$1,$2)',[start,end]);
        Object.assign(item,{bookingItemId:'1',scheduledStartAt:start,scheduledEndAt:end});
        await ledger.executeCommand({pool,tenantId:'1',locationId:'10',actorUserId:'1',operationKey:'booking:1:reserve',command:'reserve',payload:{bookingItemId:'1'}});
      }
      if (plan) await pool.query('INSERT INTO ticket_service_plans(ticket_id,tenant_id,location_id,source,booking_id,items) VALUES($1,1,10,$2,$3,$4)',[id,booking?'booking':'staff_selection',booking?'1':null,JSON.stringify([item])]);
    }
    require('tsx/cjs');
    let queueClosed=false;
    const queueMocks={...mocks,
      '../config/env':{waitTimePredictionCaptureEnabled:false},
      '../repositories/tickets':{...mocks['../repositories/tickets'],
        findCurrentCalledTicket:async (tenantId,{client,locationId}) => {
          const r=(await client.query("SELECT id::text FROM tickets WHERE tenant_id=$1 AND location_id=$2 AND status='called' ORDER BY id LIMIT 1 FOR UPDATE",[tenantId,locationId])).rows[0];
          return r ? readTicket(r.id,{client}) : null;
        },
        updateCurrentCalledTicketStatus:async (tenantId,status,{client,locationId,ticketId}) => {
          const r=await client.query("UPDATE tickets SET status=$4,updated_at=clock_timestamp() WHERE tenant_id=$1 AND location_id=$2 AND id=$3 AND status='called' RETURNING id::text",[tenantId,locationId,ticketId,status]);
          return r.rows[0] ? readTicket(r.rows[0].id,{client}) : null;
        },
        findVendorTicketForUpdate:async (tenantId,locationId,id,{client}) => {
          const r=(await client.query('SELECT id::text FROM tickets WHERE tenant_id=$1 AND location_id=$2 AND id=$3 FOR UPDATE',[tenantId,locationId,id])).rows[0];
          return r ? readTicket(r.id,{client}) : null;
        },
        findTicketByScopedLookupCodeForUpdate:async (tenantId,locationId,code,{client}) => {
          const r=(await client.query('SELECT id::text FROM tickets WHERE tenant_id=$1 AND location_id=$2 AND lookup_code=$3 FOR UPDATE',[tenantId,locationId,code])).rows[0];
          return r ? readTicket(r.id,{client}) : null;
        },
        cancelWaitingTicket:async (tenantId,code,{client,cancelledByVendor}) => {
          const id=code.split('-').at(-1);
          const r=await client.query(`UPDATE tickets SET status='cancelled',status_reason=CASE WHEN status='pending_carry_over' THEN 'carry_over_declined' ELSE $3 END,
            updated_at=clock_timestamp() WHERE tenant_id=$1 AND id=$2 AND status IN ('waiting','pending_carry_over') RETURNING id::text`,[tenantId,id,cancelledByVendor?'vendor_cancelled':'customer_cancelled']);
          return r.rows[0] ? readTicket(r.rows[0].id,{client}) : null;
        }
      },
      '../repositories/queueDayPauses':{findActivePause:async (_tenant,_location,_date,{client}) => {
        assert.ok(client); return (await client.query('SELECT paused FROM intake_state')).rows[0].paused ? {_id:'1'} : null;
      }},
      '../repositories/queueDayClosures':{findActiveClosure:async (_tenant,_location,_date,{client}) => {
        assert.ok(client); return queueClosed ? {_id:'1'} : null;
      }},
      './queueDayLifecycleService':{
        getAuthoritativeQueueDay:async (_tenant,_location,{client}) => {
          assert.ok(client);
          const row=(await client.query('SELECT * FROM queue_day_state')).rows[0];
          dayReads++;
          const closesAt=dueRead && dayReads<dueRead ? new Date(Date.now()+60000) : row.closes_at;
          return row.state==='open' ? {_id:'999',businessDate:'2026-10-08',currentClosesAt:closesAt,intakeMode:row.intake_mode,state:row.state} : null;
        },
        closeLockedQueueDay:async client => {
          await client.query("UPDATE queue_day_state SET state='closed'; UPDATE tickets SET status='unserved'; UPDATE bookings SET status='unfulfilled'");
          await client.query("INSERT INTO events(ticket_id,event_type,metadata) VALUES(1,'queue_day_closed','{}'); INSERT INTO lifecycle_notifications VALUES(1,'pending')");
          if(failReconciliation) throw new Error('closure failed');
        }
      },
      './queueSnapshotHelpers':{resolveLocation:async (_tenant,options) => options.location || location,buildQueueSnapshot:async () => ({current:null,queueIntake:{state:"accepting",stateLabel:"Accepting"}})},
      './queueEvents':{publish:()=>{}}
    };
    const intakeLifecycle=loadService({...mocks,'../repositories/queueDays':{
      findLatestByLocation:async (_tenant,_location,{client})=>queueMocks['./queueDayLifecycleService'].getAuthoritativeQueueDay(_tenant,_location,{client})
    }},'queueDayLifecycleService');
    queueMocks['./queueDayLifecycleService'].assertIntakeOpen=intakeLifecycle.assertIntakeOpen;
    queueMocks['./queueDayLifecycleService'].getQueueDayForSnapshot=async () => ({queueDay:await queueMocks['./queueDayLifecycleService'].getAuthoritativeQueueDay('1','10',{client:pool})});
    queueMocks['./queueDayLifecycleService'].formatQueueDayStatus=queueDay => ({state:queueDay.state,intakeMode:queueDay.intakeMode});
    const queueService=loadService(queueMocks,'queueService');
    const realTickets=loadService({'../config/db':{pool}},'../repositories/tickets');
    const realPersistence=loadService({'../repositories/tickets':realTickets},'queueTicketPersistenceHelpers');
    const realLocations=loadService({'../config/db':{pool}},'../repositories/storeLocations');
    const hours=loadService({'../repositories/storeLocations':realLocations},'storeHoursService');
    queueMocks['./queueTicketPersistenceHelpers']=realPersistence;
    queueMocks['./storeHoursService']=hours;
    queueMocks['./allowanceService']={consumeAllowance:async (input,{client}) => {
      await client.query('INSERT INTO allowance_audit VALUES($1,$2)',[input.subjectId,input.resourceKey]);
      if(failAllowance) throw new Error('allowance failed');
      return {consumed:true};
    }};
    queueMocks['../repositories/queueDays']={allocateSequence:async (_id,{client}) => {
      const r=await client.query("UPDATE queue_day_state SET next_sequence=next_sequence+1 WHERE state='open' AND intake_mode='accepting' RETURNING next_sequence-1 AS sequence");
      return r.rows[0]?.sequence ?? null;
    }};
    const operationalQueue=loadService({...queueMocks,'../repositories/tickets':{
      ...queueMocks['../repositories/tickets'],createTicket:realTickets.createTicket,findCurrentCalledTicket:realTickets.findCurrentCalledTicket,
      listWaitingTickets:realTickets.listWaitingTickets,callNextWaitingTicket:realTickets.callNextWaitingTicket,
      confirmCurrentCalledTicket:realTickets.confirmCurrentCalledTicket,
      findVendorTicketForUpdate:realTickets.findVendorTicketForUpdate,restoreSkippedTicket:realTickets.restoreSkippedTicket
    }},'queueService');
    const withTransaction=async callback=>{
      const client=await pool.connect();
      try {await client.query('BEGIN'); const result=await callback(client); await client.query('COMMIT'); return result;}
      catch(error) {await client.query('ROLLBACK'); throw error;} finally {client.release();}
    };
    const realPayments=loadService({'../config/db':{pool}},'../repositories/queueJoinPayments');
    const paidDays={findById:async (id,{client=pool,forUpdate=false}={})=>{
      if(String(id)!=='999') return null;
      if(forUpdate) await client.query('SELECT state FROM queue_day_state FOR UPDATE');
      const row=(await client.query('SELECT * FROM queue_day_state')).rows[0];
      const closesAt=paidDeadlineRace && forUpdate && !paidDeadlineObserved ? new Date(Date.now()+60000) : row.closes_at;
      if(forUpdate) paidDeadlineObserved=true;
      return {_id:'999',tenantId:'1',locationId:'10',businessDate:'2026-10-08',state:row.state,intakeMode:row.intake_mode,currentClosesAt:closesAt};
    }};
    const paidService=loadService({
      '../config/db':{pool,withTransaction},
      '../config/env':{},
      '../repositories/queueJoinPayments':{...realPayments,findPaymentByProviderId:async (id,options={})=>realPayments.findPaymentByProviderId(id,{...options,client:options.client || pool}),markPaidWithTicket:async (...args)=>{
        const result=await realPayments.markPaidWithTicket(...args); if(failPayment) throw new Error('payment failed'); return result;
      }},
      '../repositories/queueDays':paidDays,
      '../repositories/tenants':{findTenantById:async (id,{client=pool}={})=>{
        const row=(await client.query('SELECT * FROM tenants WHERE id=$1',[id])).rows[0];
        return row && {_id:String(row.id),isActive:row.is_active,autoPauseEnabled:row.auto_pause_enabled,autoPauseThreshold:row.auto_pause_threshold,queuePrefix:row.queue_prefix};
      }},
      '../repositories/storeLocations':{findLocationById:async (id,{client=pool}={})=>{
        const row=(await client.query('SELECT * FROM store_locations WHERE id=$1',[id])).rows[0];
        return row && {_id:String(row.id),tenantId:String(row.tenant_id),isActive:row.is_active,queueLifecycleMode:row.queue_lifecycle_mode,timezone:row.timezone,slug:row.slug};
      }},
      '../repositories/billing':{recordBillingEvent:async ()=>({_id:'1'})},
      './queueFeeService':{assertTenantCanAcceptCustomerJoins:async (_tenant,{client})=>{
        assert.ok(client); if(subscriptionUnavailable) throw Object.assign(new Error('subscription unavailable'),{code:'SUBSCRIPTION_REQUIRED'});
      }},
      './allowanceService':{releaseReservation:async (input,{client})=>{
        await client.query("UPDATE payment_allowance SET state='released' WHERE reservation_key=$1",[input.reservationKey]);
        if(failAllowance) throw new Error('allowance failed');
      }},
      './queueDayLifecycleService':queueMocks['./queueDayLifecycleService'],
      './queueService':{
        createTicketForTenantInTransaction:loadService({...queueMocks,'./allowanceService':{
          ...queueMocks['./allowanceService'],commitReservation:async (input,{client})=>{
            await client.query("UPDATE payment_allowance SET state='consumed',ticket_id=$2 WHERE reservation_key=$1",[input.reservationKey,input.subjectId]);
            if(failAllowance) throw new Error('allowance failed');
          }
        }},'queueService').createTicketForTenantInTransaction,
        assertWaitingIntakeCapacityAvailable:operationalQueue.assertWaitingIntakeCapacityAvailable,
        recordCreatedTicketEvent:operationalQueue.recordCreatedTicketEvent,
        maybeNotifyUpcomingTickets:noop,publishSnapshot:async ()=>({})
      },
      './pushNotificationService':{notifyCustomerQueueUpdate:async ()=>{assert.ok(await count('tickets')); pushes++;}}
    },'queueJoinPaymentService');
    async function payment(id='1') {
      await pool.query("UPDATE store_locations SET queue_lifecycle_mode='enforced' WHERE id=10; UPDATE queue_day_state SET closes_at=clock_timestamp()+interval '1 hour'");
      await pool.query("INSERT INTO queue_join_payments(id,tenant_id,provider_checkout_session_id,queue_day_id,payload) VALUES($1,1,$2,999,$3)",[id,`CHECKOUT-${id}`,JSON.stringify({customerName:'Paid customer',joinChannel:'online',locationSlug:'main'})]);
      await pool.query("INSERT INTO payment_allowance VALUES($1,'held',NULL)",[`queue-payment:${id}`]);
    }
    const paid=(id='1')=>paidService.handlePayMongoPaidCheckout({id:`CHECKOUT-${id}`,attributes:{payments:[{id:`PROVIDER-${id}`,attributes:{paid_at:'2026-10-09T00:00:00Z'}}]}},{data:{id:`EVENT-${id}`}});
    const walkin=(options={})=>operationalQueue.createTicket({tenant,location,actorUserId:'1',joinChannel:'vendor',customerName:'Walk in',serviceId:'1000',...options});
    const call=(options={})=>operationalQueue.callNextTicket(tenant,{location,actorUserId:'1',queueDateKey:'20261008',...options});
    const confirm=(code='LOOKUP-1',options={})=>operationalQueue.confirmCurrentTicket(tenant,code,{location,actorUserId:'1',queueDateKey:'20261008',...options});
    const restore=(id='1',options={})=>operationalQueue.restoreSkippedTicket(tenant,id,{location,actorUserId:'1',queueDateKey:'20261008',lookupCode:`LOOKUP-${id}`,...options});
    async function skipped(id='1',options={}) {
      await ticket(id,options);
      await pool.query("UPDATE tickets SET status='skipped',skipped_at=clock_timestamp(),rejoin_deadline_at=clock_timestamp()+interval '10 minutes',called_at=clock_timestamp(),customer_confirmed_at=clock_timestamp(),service_counter_id=123 WHERE id=$1",[id]);
    }
    const legacy=(status,actor='1') => queueService.updateCurrentTicketStatus(tenant,status,{location,actorUserId:actor});
    const cancelVendor=(id,actor='1',selected=location) => queueService.cancelTicket(tenant,'',{location:selected,actorUserId:actor,vendorTicketId:id});
    const cancelCustomer=(id,{actorUserId,contact={customerEmail:'owner@example.com'},selected=location}={}) =>
      queueService.cancelTicket(tenant,`lookup-${id}`,{location:selected,actorUserId,customerContact:contact,source:'public'});
    const count=async table => (await pool.query(`SELECT count(*)::int AS n FROM ${table}`)).rows[0].n;
    async function waitForLocationLock() {
      const deadline=Date.now()+3000;
      while(Date.now()<deadline) {
        const waiting=(await pool.query("SELECT 1 FROM pg_stat_activity WHERE application_name=$1 AND wait_event_type='Lock' AND query LIKE 'SELECT id FROM store_locations%'",[schema])).rows.length>0;
        if(waiting) return;
        await new Promise(resolve=>setTimeout(resolve,10));
      }
      assert.fail('operation must wait for the location lock');
    }
    await t.test('five simultaneous starts fit four courts; timing uses exact persisted allocation clock',async () => {
      await reset(); for (let i=1;i<=5;i++) await ticket(String(i));
      const starts=await Promise.allSettled([1,2,3,4,5].map(id => record(String(id),'start')));
      assert.equal(starts.filter(r=>r.status==='fulfilled').length,4);
      assert.equal(starts.filter(r=>r.status==='rejected').length,1);
      assert.equal(await count('resource_allocations'),4); assert.equal(await count('events'),4); assert.equal(await count('webhooks'),4);
      assert.equal((await pool.query('SELECT bool_and(t.service_started_at=a.started_at) AS exact FROM tickets t JOIN resource_allocations a ON a.ticket_id=t.id')).rows[0].exact,true);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'9');
    });
    await t.test('booking conversion preserves protected end; completion survives draft changes and tracking disable',async () => {
      await reset(1); await ticket('1',{booking:true}); await record('1','start');
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'converted');
      assert.equal((await pool.query('SELECT a.expected_end_at=r.ends_at AS exact FROM resource_allocations a JOIN resource_ledger_reservations r ON r.id=a.reservation_id')).rows[0].exact,true);
      await pool.query('UPDATE location_resource_pools SET tracking_enabled=FALSE,revision=2,capacity=1');
      await pool.query('UPDATE service_resource_requirements SET revision=2,units_required=2');
      await pool.query('UPDATE store_locations SET service_timing_enabled=FALSE,is_active=FALSE');
      await record('1','complete');
      assert.equal((await readTicket('1')).status,'served');
      assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'completed');
      assert.equal((await pool.query('SELECT t.service_ended_at=a.released_at AND t.served_at=a.released_at AS exact FROM tickets t JOIN resource_allocations a ON a.ticket_id=t.id')).rows[0].exact,true);
      assert.equal((await pool.query('SELECT outcome FROM resource_allocations')).rows[0].outcome,'completed'); assert.equal(pushes,1);
      await record('1','complete'); assert.equal(await count('booking_audit'),1); assert.equal(pushes,1);
    });
    await t.test('start retry and competing completion/interruption create one explicit release',async () => {
      await reset(); await ticket('1');
      await Promise.all([record('1','start'),record('1','start')]);
      assert.equal(await count('resource_allocations'),1); assert.equal(await count('events'),1);
      const outcomes=await Promise.allSettled([record('1','complete'),record('1','interrupt')]);
      assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);
      assert.equal(await count('resource_ledger_commands'),2); assert.equal(await count('events'),3);
      assert.equal(await count('webhooks'),3);
      const current=await readTicket('1'); await record('1',current.serviceOutcome==='completed'?'complete':'interrupt');
      assert.equal(await count('events'),3);
      await assert.rejects(record('1','start'),{statusCode:409});
    });
    await t.test('overdue occupancy survives queue closure until explicit interruption',async () => {
      await reset(1); await ticket('1'); await ticket('2'); await record('1','start');
      await pool.query("UPDATE resource_allocations SET started_at=clock_timestamp()-interval '2 hours',expected_end_at=clock_timestamp()-interval '1 hour'");
      await pool.query("UPDATE tickets SET status='unserved' WHERE id=1");
      await assert.rejects(record('2','start'),{statusCode:409});
      await record('1','interrupt'); const allocation=(await pool.query('SELECT * FROM resource_allocations')).rows[0];
      assert.equal(allocation.outcome,'terminated'); assert.equal(allocation.reason,'Staff explicitly interrupted service.');
      assert.equal((await readTicket('1')).status,'unserved');
      await record('2','start'); assert.equal(await count('resource_allocations'),2);
    });
    await t.test('event and booking failures roll timing, conversion, release, receipts and revision back',async () => {
      await reset(); await ticket('1',{booking:true}); failEvent=true;
      await assert.rejects(record('1','start'),/event failed/);
      assert.equal((await readTicket('1')).serviceStartedAt,null); assert.equal(await count('resource_allocations'),0);
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
      assert.equal(await count('resource_ledger_commands'),1); assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'2');
      failEvent=false; await record('1','start'); failBooking=true;
      const revision=(await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision;
      await assert.rejects(record('1','complete'),/booking failed/);
      assert.equal((await readTicket('1')).serviceEndedAt,null); assert.equal((await readTicket('1')).status,'called');
      assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null);
      assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'confirmed');
      assert.equal(await count('resource_ledger_commands'),2); assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1); assert.equal(await count('booking_audit'),0);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,revision); assert.equal(pushes,0);
    });
    await t.test('staff assignment and current actor access are checked under the location lock',async () => {
      await reset(); await ticket('1'); await assert.rejects(record('1','start','2'),{statusCode:403});
      await pool.query('INSERT INTO service_counters VALUES(1,1,10,TRUE); INSERT INTO service_counter_assignments VALUES(2,1)');
      await record('1','start','2'); await pool.query('UPDATE service_counters SET is_active=FALSE');
      await assert.rejects(record('1','complete','2'),{statusCode:403});
      await pool.query('INSERT INTO tenant_membership_locations VALUES(2,10)'); await record('1','complete','2');
      await reset(); await ticket('1');
      const blocker=await pool.connect(); await blocker.query('BEGIN'); await blocker.query('SELECT id FROM store_locations WHERE id=10 FOR UPDATE');
      const waiting=record('1','start'); waiting.catch(()=>{});
      try {
        let locked=false;
        for(let i=0;i<100;i++) {
          locked=(await pool.query("SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE application_name=$1 AND wait_event_type='Lock') AS locked",[schema])).rows[0].locked;
          if(locked) break; await new Promise(resolve=>setTimeout(resolve,10));
        }
        assert.equal(locked,true); await blocker.query('UPDATE tenant_memberships SET is_active=FALSE WHERE user_id=1'); await blocker.query('COMMIT');
        await assert.rejects(waiting,{statusCode:403}); assert.equal(await count('resource_allocations'),0);
      } finally {await blocker.query('ROLLBACK'); blocker.release();}
      await pool.query('UPDATE tenant_memberships SET is_active=TRUE; UPDATE users SET platform_access_suspended_at=clock_timestamp() WHERE id=1');
      await assert.rejects(record('1','start'),{statusCode:403});
    });
    await t.test('start rejects wrong scope, disabled timing, unconfirmed tickets and stale or unknown plans',async () => {
      await reset(); await ticket('1',{plan:false}); await assert.rejects(record('1','start'),{statusCode:409});
      await assert.rejects(record('1','start','1',{_id:'20'}),{statusCode:404});
      await reset(); await ticket('1'); await pool.query('UPDATE service_resource_requirements SET revision=2');
      await assert.rejects(record('1','start'),/stale/); assert.equal(await count('resource_allocations'),0);
      await pool.query('UPDATE service_resource_requirements SET revision=1; UPDATE store_locations SET service_timing_enabled=FALSE');
      await assert.rejects(record('1','start'),/not enabled/);
      await pool.query("UPDATE store_locations SET service_timing_enabled=TRUE; UPDATE tickets SET join_channel='customer'");
      await assert.rejects(record('1','start'),/Confirm/);
      await pool.query("UPDATE tickets SET customer_confirmed_at=clock_timestamp(),status='waiting'");
      await assert.rejects(record('1','start'),/Call/);
      assert.equal(await count('events'),0);
    });
    await t.test('missing booking protection cannot silently become ordinary after tracking disable',async () => {
      await reset(); await ticket('1',{booking:true});
      await pool.query("UPDATE resource_ledger_reservations SET state='cancelled'; UPDATE location_resource_pools SET tracking_enabled=FALSE");
      await assert.rejects(record('1','start'),/binding/); assert.equal(await count('resource_allocations'),0);
    });
    await t.test('a lost booking plan still requires resource handling after tracking disable',async () => {
      await reset(); await ticket('1',{booking:true});
      await pool.query('DELETE FROM ticket_service_plans; UPDATE location_resource_pools SET tracking_enabled=FALSE');
      await assert.rejects(record('1','start'),/plan/); assert.equal(await count('resource_allocations'),0);
      assert.equal((await readTicket('1')).serviceStartedAt,null);
    });
    await t.test('ordinary timing remains explicit without allocating; incomplete resource state fails closed',async () => {
      await reset(4,false); await ticket('1',{plan:false});
      await record('1','start'); await record('1','interrupt');
      const current=await readTicket('1'); assert.ok(current.serviceStartedAt); assert.ok(current.serviceEndedAt); assert.equal(current.status,'unserved');
      assert.equal(await count('resource_allocations'),0); assert.equal(await count('resource_ledger_commands'),0);
      await reset(); await ticket('1'); await pool.query('UPDATE tickets SET service_started_at=clock_timestamp()');
      await assert.rejects(record('1','start'),/reconciliation/); await assert.rejects(record('1','complete'),/reconciliation/);
      assert.equal((await readTicket('1')).serviceEndedAt,null);
    });
    await t.test('configured metadata alone does not activate an ordinary disabled scope',async () => {
      await reset(4,false); await ticket('1'); await record('1','start'); await record('1','complete');
      assert.equal(await count('resource_allocations'),0); assert.equal(await count('resource_ledger_commands'),0);
      assert.equal((await readTicket('1')).status,'served');
    });
    await t.test('a prematurely released allocation cannot be acknowledged as an active service retry',async () => {
      await reset(); await ticket('1'); await record('1','start');
      const allocation=(await pool.query('SELECT id::text FROM resource_allocations')).rows[0].id;
      await ledger.executeCommand({pool,tenantId:'1',locationId:'10',actorUserId:'1',operationKey:'corrupt-state-release',command:'release',payload:{allocationId:allocation,outcome:'completed'}});
      await assert.rejects(record('1','start'),/reconciliation/); await assert.rejects(record('1','complete'),/reconciliation/);
      assert.equal((await readTicket('1')).serviceEndedAt,null); assert.equal(await count('events'),1);
    });
    await t.test('legacy Serve cannot bypass resource protection when timing and tracking are disabled',async () => {
      await reset(); await ticket('1',{booking:true});
      await pool.query('UPDATE store_locations SET service_timing_enabled=FALSE; UPDATE location_resource_pools SET tracking_enabled=FALSE');
      await assert.rejects(legacy('served'),/Use Start service/);
      assert.equal((await readTicket('1')).status,'called'); assert.equal(await count('events'),0);
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
    });
    await t.test('unstarted skip retains protection; every legacy outcome rejects existing occupancy',async () => {
      await reset(); await ticket('1',{booking:true}); await legacy('skipped');
      assert.equal((await readTicket('1')).status,'skipped'); assert.equal(await count('resource_allocations'),0);
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
      await pool.query("UPDATE tickets SET status='called'"); await record('1','start');
      await pool.query('UPDATE store_locations SET service_timing_enabled=FALSE; UPDATE location_resource_pools SET tracking_enabled=FALSE');
      for(const status of ['served','skipped','cancelled','unserved']) await assert.rejects(legacy(status),/Use Start service/);
      assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null);
    });
    await t.test('vendor waiting cancellation cancels immutable protection and linked booking once',async () => {
      await reset(); await ticket('1',{booking:true}); await pool.query("UPDATE tickets SET status='waiting'; INSERT INTO queue_ticket_segments(ticket_id) VALUES(1)");
      await pool.query('UPDATE location_resource_pools SET tracking_enabled=FALSE,revision=2; UPDATE service_resource_requirements SET revision=2,units_required=2');
      const results=await Promise.allSettled([cancelVendor('1'),cancelVendor('1')]);
      assert.equal(results.filter(r=>r.status==='fulfilled').length,1); assert.equal(results.filter(r=>r.status==='rejected').length,1);
      assert.equal((await readTicket('1')).status,'cancelled'); assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'canceled');
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'cancelled');
      assert.equal((await pool.query('SELECT segment_outcome FROM queue_ticket_segments')).rows[0].segment_outcome,'cancelled');
      assert.equal(await count('resource_ledger_commands'),2); assert.equal(await count('resource_allocations'),0);
      assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1); assert.equal(pushes,1);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'4');
    });
    await t.test('vendor cancellation event failure rolls ticket, booking, protection, segment and revision back',async () => {
      await reset(); await ticket('1',{booking:true}); await pool.query("UPDATE tickets SET status='waiting'; INSERT INTO queue_ticket_segments(ticket_id) VALUES(1)"); failEvent=true;
      await assert.rejects(cancelVendor('1'),/event failed/);
      assert.equal((await readTicket('1')).status,'waiting'); assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'confirmed');
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
      assert.equal((await pool.query('SELECT ended_at FROM queue_ticket_segments')).rows[0].ended_at,null);
      assert.equal(await count('resource_ledger_commands'),1); assert.equal(await count('events'),0); assert.equal(await count('webhooks'),0); assert.equal(pushes,0);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'2');
    });
    await t.test('vendor outcomes recheck actor and assignment; closed queue or wrong branch cannot write',async () => {
      await reset(); await ticket('1',{booking:true});
      await assert.rejects(legacy('skipped','2'),{statusCode:403});
      await pool.query('INSERT INTO tenant_membership_locations VALUES(2,10)'); queueClosed=true;
      await assert.rejects(legacy('skipped','2'),{statusCode:409});
      await pool.query('UPDATE tenant_memberships SET is_active=FALSE WHERE user_id=2');
      await assert.rejects(legacy('skipped','2'),{statusCode:403}); queueClosed=false;
      await pool.query("UPDATE tickets SET status='waiting'"); await assert.rejects(cancelVendor('1','2'),{statusCode:403});
      await assert.rejects(cancelVendor('1','1',{_id:'20'}),{statusCode:404});
      await assert.rejects(cancelVendor('9007199254740993'),{statusCode:404});
      assert.equal(await count('events'),0); assert.equal((await readTicket('1')).status,'waiting');
    });
    await t.test('legacy terminal cancellation clears unused protection atomically; ordinary Serve stays supported',async () => {
      await reset(); await ticket('1',{booking:true}); await legacy('cancelled');
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'cancelled');
      assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'canceled');
      assert.equal(await count('resource_allocations'),0);
      await reset(4,false); await ticket('1',{plan:false}); await pool.query('UPDATE store_locations SET service_timing_enabled=FALSE');
      await legacy('served'); assert.equal((await readTicket('1')).status,'served'); assert.equal(await count('resource_ledger_commands'),0);
      assert.equal(await count('resource_allocations'),0);
    });
    await t.test('linked active booking cancellation requires booking management; staff can cancel ordinary tickets',async () => {
      await reset(); await ticket('1',{booking:true}); await pool.query('INSERT INTO tenant_membership_locations VALUES(2,10)');
      await assert.rejects(legacy('cancelled','2'),{statusCode:403});
      await pool.query("UPDATE tickets SET status='waiting'"); await assert.rejects(cancelVendor('1','2'),{statusCode:403});
      assert.equal((await readTicket('1')).status,'waiting'); assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'confirmed');
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected'); assert.equal(await count('events'),0);
      await reset(4,false); await ticket('1',{plan:false}); await pool.query("INSERT INTO tenant_membership_locations VALUES(2,10); UPDATE tickets SET status='waiting'");
      await cancelVendor('1','2'); assert.equal((await readTicket('1')).status,'cancelled'); assert.equal(await count('events'),1);
    });
    await t.test('vendor cancellation preserves terminal booking status',async () => {
      await reset(); await ticket('1',{booking:true}); await pool.query("UPDATE tickets SET status='waiting'; UPDATE bookings SET status='completed'");
      await cancelVendor('1'); assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'completed');
    });
    await t.test('overdue reconciliation commits before rejecting and retains actual occupancy',async () => {
      await reset(); await ticket('1',{booking:true}); await record('1','start'); location.queueLifecycleMode='enforced';
      await assert.rejects(legacy('skipped'),{code:'QUEUE_DAY_OVERDUE'});
      assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'closed');
      assert.equal((await readTicket('1')).status,'unserved'); assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'unfulfilled');
      assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null);
      assert.equal(await count('lifecycle_notifications'),1); assert.equal(await count('events'),2);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'5');
      await assert.rejects(legacy('skipped'),{code:'QUEUE_DAY_UNOPENED'});
      assert.equal(await count('lifecycle_notifications'),1); assert.equal(await count('events'),2);
    });
    await t.test('reconciliation failure still rolls back its partial outcomes',async () => {
      await reset(); await ticket('1',{booking:true}); location.queueLifecycleMode='enforced'; failReconciliation=true;
      await assert.rejects(legacy('skipped'),/closure failed/);
      assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'open');
      assert.equal((await readTicket('1')).status,'called'); assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'confirmed');
      assert.equal(await count('lifecycle_notifications'),0); assert.equal(await count('events'),0);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'2');
    });
    await t.test('an unrelated enabled pool does not block ordinary or disabled-pool services',async () => {
      await reset(4,false); await ticket('1'); await ticket('2');
      await pool.query('INSERT INTO location_resource_pools VALUES(101,1,10,4,1,TRUE); INSERT INTO service_resource_requirements VALUES(1,10,2000,101,1,1); UPDATE store_locations SET service_timing_enabled=FALSE');
      await legacy('served'); assert.equal((await readTicket('1')).status,'served');
      await pool.query('DELETE FROM service_resource_requirements WHERE service_id=1000');
      await pool.query(`UPDATE ticket_service_plans SET items=jsonb_set(items,'{0,resource}','{"known":false}') WHERE ticket_id=2`);
      await legacy('served'); assert.equal((await readTicket('2')).status,'served');
      assert.equal(await count('resource_allocations'),0); assert.equal(await count('resource_ledger_commands'),0);
    });
    await t.test('mixed-service explicit starts allocate only the ticket resource and retain unknown-plan denial',async () => {
      await reset(4,false); await ticket('1'); await ticket('2'); await ticket('3',{plan:false});
      await pool.query('INSERT INTO location_resource_pools VALUES(101,1,10,4,1,TRUE); INSERT INTO service_resource_requirements VALUES(1,10,2000,101,1,1)');
      await pool.query(`UPDATE ticket_service_plans SET items=jsonb_set(jsonb_set(items,'{0,serviceId}','"2000"'),'{0,resource,poolId}','"101"') WHERE ticket_id=2`);
      await record('1','start'); await record('2','start');
      assert.equal(await count('resource_allocations'),1);
      const allocation=(await pool.query('SELECT ticket_id::text,pool_id::text FROM resource_allocations')).rows[0];
      assert.deepEqual(allocation,{ticket_id:'2',pool_id:'101'});
      await assert.rejects(record('3','start'),/plan/);
      await record('1','complete'); await record('2','complete');
    });
    await t.test('guest cancellation commits immutable booking protection once after tracking disable',async () => {
      await reset(); await ticket('1',{booking:true});
      await pool.query("UPDATE tickets SET status='waiting'; INSERT INTO queue_ticket_segments(ticket_id) VALUES(1); UPDATE location_resource_pools SET tracking_enabled=FALSE,revision=2");
      const results=await Promise.allSettled([cancelCustomer('1'),cancelCustomer('1')]);
      assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
      assert.equal(results.filter(r=>r.status==='rejected' && r.reason.statusCode===409).length,1);
      assert.equal((await readTicket('1')).status,'cancelled');
      assert.equal((await pool.query('SELECT status,fulfillment_outcome_reason,refund_eligible FROM bookings')).rows[0].status,'canceled');
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'cancelled');
      assert.equal((await pool.query("SELECT actor_user_id FROM resource_ledger_commands WHERE command='cancelReservation'")).rows[0].actor_user_id,null);
      assert.equal((await pool.query('SELECT segment_outcome,outcome_reason FROM queue_ticket_segments')).rows[0].outcome_reason,'customer_cancelled');
      assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1); assert.equal(await count('resource_allocations'),0); assert.equal(pushes,1);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'4');
    });
    await t.test('linked ticket and booking require their current account owner',async () => {
      await reset(); await ticket('1',{booking:true});
      await pool.query("UPDATE tickets SET status='waiting',user_id=1; UPDATE bookings SET customer_user_id=1");
      await assert.rejects(cancelCustomer('1'),{statusCode:403});
      await assert.rejects(cancelCustomer('1',{actorUserId:'2'}),{statusCode:403});
      assert.equal((await readTicket('1')).status,'waiting'); assert.equal(await count('events'),0);
      await cancelCustomer('1',{actorUserId:'1',contact:{}});
      assert.equal((await pool.query("SELECT actor_user_id::text FROM resource_ledger_commands WHERE command='cancelReservation'")).rows[0].actor_user_id,'1');
    });
    await t.test('guest carry-over cancellation remains available after closure and preserves terminal booking status',async () => {
      await reset(); await ticket('1',{booking:true});
      await pool.query("UPDATE tickets SET status='pending_carry_over'; UPDATE bookings SET status='completed'; UPDATE store_locations SET is_active=FALSE"); queueClosed=true;
      await cancelCustomer('1',{contact:{customerPhone:'+639171234567'}});
      assert.equal((await readTicket('1')).status,'cancelled');
      assert.equal((await pool.query('SELECT status_reason FROM tickets')).rows[0].status_reason,'carry_over_declined');
      assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'completed');
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'cancelled');
      await reset(4,false); await ticket('1',{plan:false}); await pool.query("UPDATE tickets SET status='waiting'");
      await cancelCustomer('1'); assert.equal((await readTicket('1')).status,'cancelled');
      assert.equal(await count('resource_ledger_commands'),0); assert.equal(await count('resource_allocations'),0);
    });
    await t.test('customer cancellation failures roll all domain effects and receipts back',async () => {
      for(const failure of ['event','webhook']) {
        await reset(); await ticket('1',{booking:true});
        await pool.query("UPDATE tickets SET status='waiting'; INSERT INTO queue_ticket_segments(ticket_id) VALUES(1)");
        failEvent=failure==='event'; failWebhook=failure==='webhook';
        await assert.rejects(cancelCustomer('1'),new RegExp(`${failure} failed`));
        assert.equal((await readTicket('1')).status,'waiting'); assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'confirmed');
        assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
        assert.equal((await pool.query('SELECT ended_at FROM queue_ticket_segments')).rows[0].ended_at,null);
        assert.equal(await count('resource_ledger_commands'),1); assert.equal(await count('events'),0); assert.equal(await count('webhooks'),0); assert.equal(pushes,0);
        assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'2');
      }
    });
    await t.test('ownership, status and current user are reread after a competing location lock',async () => {
      const changes=[
        {sql:'UPDATE tickets SET user_id=1',code:403},
        {sql:"UPDATE tickets SET customer_email='changed@example.com',customer_phone=NULL",code:403},
        {sql:"UPDATE tickets SET status='called'",code:409},
        {sql:'UPDATE users SET deletion_requested_at=clock_timestamp() WHERE id=1',actor:'1',code:403},
        {sql:'UPDATE users SET platform_access_suspended_at=clock_timestamp() WHERE id=1',actor:'1',code:403}
      ];
      for(const change of changes) {
        await reset(); await ticket('1'); await pool.query("UPDATE tickets SET status='waiting'");
        const blocker=await pool.connect(); let pending;
        try {
          await blocker.query('BEGIN'); await blocker.query('SELECT id FROM store_locations WHERE id=10 FOR UPDATE');
          pending=assert.rejects(cancelCustomer('1',{actorUserId:change.actor}),{statusCode:change.code});
          await waitForLocationLock();
          await blocker.query(change.sql); await blocker.query('COMMIT'); await pending;
          assert.equal(await count('events'),0); assert.equal(await count('resource_ledger_commands'),0);
        } finally {await blocker.query('ROLLBACK'); blocker.release(); if(pending) await pending;}
      }
    });
    await t.test('wrong scope, inconsistent booking owner and active occupancy cannot be cancelled by a customer',async () => {
      await reset(); await ticket('1',{booking:true}); await pool.query("UPDATE tickets SET status='waiting'; UPDATE bookings SET customer_user_id=2");
      await assert.rejects(cancelCustomer('1',{selected:{_id:'20'}}),{statusCode:404});
      await assert.rejects(cancelCustomer('1'),{statusCode:403});
      assert.equal((await readTicket('1')).status,'waiting'); assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
      await pool.query("UPDATE bookings SET customer_user_id=NULL; UPDATE tickets SET status='called'"); await record('1','start');
      await pool.query("UPDATE tickets SET status='waiting'; UPDATE location_resource_pools SET tracking_enabled=FALSE");
      await assert.rejects(cancelCustomer('1'),/Use Start service/);
      assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null);
      assert.equal((await readTicket('1')).status,'waiting');
    });
    await t.test('customer cancellation ledger capability rejects other commands and unrelated protection',async () => {
      await reset(); await ticket('1',{booking:true});
      const transact=(callback,actorUserId)=>ledger.withCustomerTicketCancellationTransaction({pool,tenantId:'1',locationId:'10',lookupCode:'LOOKUP-1',actorUserId,authorize:async()=>true},callback);
      for(const actor of [undefined,'1']) {
        for(const command of ['reserve','allocate','release']) {
          await assert.rejects(transact((_client,capability)=>capability.executeCommand({command,payload:{},operationKey:'ticket:1:reservation:1:customer-cancel'}),actor),{statusCode:403});
        }
      }
      const binding=(await pool.query('SELECT id::text FROM resource_ledger_reservations')).rows[0].id;
      await assert.rejects(transact((_client,capability)=>capability.executeCommand({command:'cancelReservation',payload:{reservationId:binding},operationKey:`ticket:2:reservation:${binding}:customer-cancel`})),{statusCode:403});
      await assert.rejects(transact((_client,capability)=>capability.executeCommand({command:'cancelReservation',payload:{reservationId:binding},operationKey:`booking:1:reservation:${binding}:expiry:cancel`})),{statusCode:403});
      await assert.rejects(transact((_client,capability)=>capability.executeCommand({command:'cancelReservation',payload:{reservationId:binding},operationKey:`ticket:1:reservation:${binding}:customer-cancel`})),{statusCode:403});
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected'); assert.equal(await count('resource_ledger_commands'),1);
    });
    await t.test('competing calls use real ticket SQL and preserve one called ticket without allocation',async () => {
      await reset(); await ticket('1'); await ticket('2'); await pool.query("UPDATE tickets SET status='waiting'");
      const results=await Promise.allSettled([call(),call()]);
      assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
      assert.equal(results.filter(r=>r.status==='rejected' && r.reason.statusCode===400).length,1);
      assert.equal((await pool.query("SELECT count(*)::int AS n FROM tickets WHERE status='called'")).rows[0].n,1);
      assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1); assert.equal(pushes,1);
      assert.equal(await count('resource_allocations'),0); assert.equal(await count('resource_ledger_commands'),0);
      assert.equal((await pool.query('SELECT bool_and(service_started_at IS NULL) AS untouched FROM tickets')).rows[0].untouched,true);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'2');
    });
    await t.test('confirmation checks scanned identity and deduplicates concurrent retries without service start',async () => {
      await reset(); await ticket('1',{channel:'online'});
      await assert.rejects(confirm('WRONG'),{statusCode:409}); assert.equal(await count('events'),0);
      await Promise.all([confirm('lookup-1'),confirm()]);
      const stamp=(await pool.query('SELECT customer_confirmed_at::text FROM tickets')).rows[0].customer_confirmed_at;
      assert.ok(stamp); await confirm();
      assert.equal((await pool.query('SELECT customer_confirmed_at::text FROM tickets')).rows[0].customer_confirmed_at,stamp);
      assert.equal((await readTicket('1')).status,'called'); assert.equal((await readTicket('1')).serviceStartedAt,null);
      assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1); assert.equal(pushes,1);
      assert.equal(await count('resource_allocations'),0); assert.equal(await count('resource_ledger_commands'),0);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'2');
    });
    await t.test('call eligibility keeps early arrived bookings waiting and selects an eligible ordinary ticket',async () => {
      await reset(); await ticket('1',{booking:true}); await pool.query("UPDATE tickets SET status='waiting',service_priority_band='checked_in_booking'; UPDATE bookings SET scheduled_start_at=clock_timestamp()+interval '1 hour'");
      await assert.rejects(call(),{code:'NO_READY_WAITING_TICKET'});
      assert.equal((await readTicket('1')).status,'waiting'); assert.equal(await count('events'),0);
      await ticket('2'); await pool.query("UPDATE tickets SET status='waiting' WHERE id=2; INSERT INTO service_counters VALUES(1,1,10,TRUE)");
      const result=await call({serviceCounter:{_id:'1'}});
      assert.equal(result.ticket._id,'2'); assert.equal(result.ticket.serviceCounterId,'1');
      assert.equal((await readTicket('1')).status,'waiting');
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
      assert.equal(await count('resource_allocations'),0);
    });
    await t.test('a booking becoming ready during lock contention uses the current DB clock for eligibility and call time',async () => {
      await reset(); await ticket('1',{booking:true}); await pool.query("UPDATE tickets SET status='waiting'; UPDATE bookings SET scheduled_start_at=clock_timestamp()+interval '1 hour'");
      const blocker=await pool.connect(); let pending;
      try {
        await blocker.query('BEGIN'); await blocker.query('SELECT id FROM store_locations WHERE id=10 FOR UPDATE');
        pending=call(); pending.catch(()=>{}); await waitForLocationLock();
        await blocker.query('UPDATE bookings SET scheduled_start_at=clock_timestamp()'); await blocker.query('COMMIT');
        const result=await pending; assert.equal(result.ticket._id,'1');
        assert.equal((await pool.query('SELECT t.called_at>=b.scheduled_start_at AS after_ready FROM tickets t JOIN bookings b ON b.queue_ticket_id=t.id')).rows[0].after_ready,true);
        assert.equal(await count('resource_allocations'),0);
      } finally {await blocker.query('ROLLBACK'); blocker.release(); if(pending) await pending.catch(()=>{});}
    });
    await t.test('calling and confirmation roll back on event or webhook failures',async () => {
      for(const action of ['call','confirm']) {
        for(const failure of ['event','webhook']) {
          await reset(); await ticket('1',{booking:true});
          if(action==='call') await pool.query("UPDATE tickets SET status='waiting'");
          failEvent=failure==='event'; failWebhook=failure==='webhook';
          await assert.rejects(action==='call'?call():confirm(),new RegExp(`${failure} failed`));
          assert.equal((await readTicket('1')).status,action==='call'?'waiting':'called');
          assert.equal((await readTicket('1')).customerConfirmedAt,null);
          assert.equal(await count('events'),0); assert.equal(await count('webhooks'),0); assert.equal(pushes,0);
          assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'2');
          assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
        }
      }
    });
    await t.test('calling and confirmation enforce current staff access, branch and counter scope',async () => {
      await reset(); await ticket('1'); await pool.query("UPDATE tickets SET status='waiting'");
      await assert.rejects(call({actorUserId:'2'}),{statusCode:403});
      await assert.rejects(confirm('LOOKUP-1',{actorUserId:'2'}),{statusCode:403});
      await pool.query('INSERT INTO tenant_membership_locations VALUES(2,10); INSERT INTO service_counters VALUES(1,1,10,FALSE),(2,2,20,TRUE)');
      for(const id of ['1','2','9007199254740993']) await assert.rejects(call({serviceCounter:{_id:id}}),{statusCode:404});
      await pool.query('UPDATE service_counters SET is_active=TRUE WHERE id=1');
      await call({actorUserId:'2',serviceCounter:{_id:'1'}}); await confirm('LOOKUP-1',{actorUserId:'2'});
      await pool.query('UPDATE tenant_memberships SET is_active=FALSE WHERE user_id=2');
      await assert.rejects(confirm('LOOKUP-1',{actorUserId:'2'}),{statusCode:403});
      await pool.query('UPDATE store_locations SET is_active=FALSE WHERE id=10');
      await assert.rejects(confirm(),{statusCode:409});
      assert.equal(await count('events'),2); assert.equal(await count('resource_allocations'),0);
    });
    await t.test('current enforced mode commits overdue reconciliation before rejecting call or confirmation',async () => {
      for(const action of ['call','confirm']) {
        await reset(); await ticket('1',{booking:true});
        if(action==='call') await pool.query("UPDATE tickets SET status='waiting'");
        else await record('1','start');
        await pool.query("UPDATE store_locations SET queue_lifecycle_mode='enforced' WHERE id=10");
        // The caller's stale location object still has legacy mode.
        await assert.rejects(action==='call'?call():confirm(),{code:'QUEUE_DAY_OVERDUE'});
        assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'closed');
        assert.equal((await readTicket('1')).status,'unserved'); assert.equal(await count('lifecycle_notifications'),1);
        assert.equal((await pool.query('SELECT count(*)::int AS n FROM events WHERE event_type IN (\'ticket_called\',\'ticket_confirmed\')')).rows[0].n,0);
        if(action==='confirm') assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null);
        const revision=(await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision;
        await assert.rejects(action==='call'?call():confirm(),{code:'QUEUE_DAY_UNOPENED'});
        assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,revision);
      }
    });
    await t.test('competing restorations commit once and preserve booking protection and frozen service plan',async () => {
      await reset(); await skipped('1',{booking:true});
      const plan=(await pool.query('SELECT items FROM ticket_service_plans')).rows[0].items;
      const results=await Promise.allSettled([restore(),restore()]);
      assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
      assert.equal(results.find(r=>r.status==='rejected').reason.statusCode,409);
      const row=(await pool.query('SELECT * FROM tickets')).rows[0];
      assert.equal(row.status,'waiting'); assert.equal(row.service_priority_band,'recovery');
      for(const key of ['service_counter_id','called_at','notified_called_at','customer_confirmed_at','rejoin_deadline_at','service_started_at']) assert.equal(row[key],null);
      assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1); assert.equal(pushes,1);
      assert.deepEqual((await pool.query('SELECT items FROM ticket_service_plans')).rows[0].items,plan);
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
      assert.equal((await pool.query('SELECT status FROM bookings')).rows[0].status,'confirmed');
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'3');
      assert.equal(await count('resource_allocations'),0); assert.equal(await count('resource_ledger_commands'),1);
      await reset(); await skipped(); await pool.query("UPDATE tickets SET rejoin_deadline_at=clock_timestamp()-interval '1 second'");
      assert.equal((await restore()).ticket.servicePriorityBand,'normal');
      await reset(4,false); await skipped('1',{plan:false});
      assert.equal((await restore()).ticket.status,'waiting');
      assert.equal(await count('resource_allocations'),0);
    });
    await t.test('restoration rechecks scoped identity, current access, metadata and same nonterminal Queue Day',async () => {
      for(const sql of [
        "UPDATE tenant_memberships SET is_active=FALSE WHERE user_id=1",
        "UPDATE users SET platform_access_suspended_at=clock_timestamp() WHERE id=1",
        "UPDATE tenant_memberships SET role='customer' WHERE user_id=1",
        "UPDATE tenant_memberships SET role='staff' WHERE user_id=1",
        "UPDATE store_locations SET is_active=FALSE WHERE id=10",
        "UPDATE tenants SET is_active=FALSE WHERE id=1",
        "UPDATE tickets SET skipped_at=NULL",
        "UPDATE tickets SET date_key='20261007'",
        "UPDATE tickets SET terminal_at=clock_timestamp()"
      ]) {
        await reset(); await skipped(); await pool.query(sql);
        await assert.rejects(restore()); assert.equal((await readTicket('1')).status,'skipped');
        assert.equal(await count('events'),0);
      }
      await reset(); await skipped();
      await assert.rejects(restore('1',{lookupCode:'WRONG'}),{statusCode:404});
      await assert.rejects(restore('1',{location:{_id:'20'}}));
      for(const id of ['9007199254740993','-1','1.1','1x']) await assert.rejects(restore(id),{statusCode:404});
      await pool.query("UPDATE tenant_memberships SET role='staff' WHERE user_id=1; INSERT INTO tenant_membership_locations VALUES(1,10)");
      assert.equal((await restore()).ticket.status,'waiting');
    });
    await t.test('restoration reads current intake policy and serializes the last waiting place',async () => {
      await reset(); await skipped(); await pool.query('UPDATE intake_state SET paused=TRUE');
      await assert.rejects(restore(),{code:'QUEUE_INTAKE_PAUSED'});
      await pool.query('UPDATE intake_state SET paused=FALSE; UPDATE tenants SET auto_pause_enabled=TRUE,auto_pause_threshold=1 WHERE id=1');
      await skipped('2');
      const results=await Promise.allSettled([restore('1'),restore('2')]);
      assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
      assert.equal(results.find(r=>r.status==='rejected').reason.code,'QUEUE_RESTORE_THRESHOLD_REACHED');
      assert.equal((await pool.query("SELECT count(*)::int AS n FROM tickets WHERE status='waiting'")).rows[0].n,1);
      assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1);
      await reset(); await skipped(); queueClosed=true;
      await assert.rejects(restore(),{statusCode:409});
    });
    await t.test('restoration rejects service history even after tracking disable and never releases occupancy',async () => {
      await reset(); await ticket('1'); await record('1','start');
      await pool.query("UPDATE tickets SET status='skipped',skipped_at=clock_timestamp(); UPDATE location_resource_pools SET tracking_enabled=FALSE");
      await assert.rejects(restore(),{statusCode:409});
      assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null);
      await pool.query("UPDATE resource_allocations SET released_at=clock_timestamp(),outcome='completed'; UPDATE tickets SET service_ended_at=clock_timestamp()");
      await assert.rejects(restore(),{statusCode:409});
      await reset(); await skipped(); await pool.query('UPDATE tickets SET service_started_at=clock_timestamp(),service_ended_at=clock_timestamp()');
      await assert.rejects(restore(),{statusCode:409});
      await reset(); await skipped('1',{booking:true});
      await pool.query("UPDATE resource_ledger_reservations SET state='converted'");
      await assert.rejects(restore(),{statusCode:409});
      await pool.query('UPDATE bookings SET queue_ticket_id=NULL');
      await assert.rejects(restore(),{statusCode:409});
      assert.equal(await count('resource_allocations'),0);
    });
    await t.test('enforced restoration requires the current accepting Queue Day and reads changes after lock contention',async () => {
      await reset(); await skipped();
      await pool.query("UPDATE store_locations SET queue_lifecycle_mode='enforced' WHERE id=10; UPDATE queue_day_state SET closes_at=clock_timestamp()+interval '1 hour'; UPDATE tickets SET current_queue_day_id=998");
      await assert.rejects(restore(),{statusCode:409});
      await pool.query("UPDATE tickets SET current_queue_day_id=999; UPDATE queue_day_state SET intake_mode='paused'");
      await assert.rejects(restore(),{code:'QUEUE_INTAKE_PAUSED'});
      await pool.query("UPDATE queue_day_state SET intake_mode='accepting'");
      assert.equal((await restore('1',{queueDateKey:undefined})).ticket.status,'waiting');
      await reset(); await skipped();
      const blocker=await pool.connect(); let pending;
      try {
        await blocker.query('BEGIN'); await blocker.query('SELECT id FROM store_locations WHERE id=10 FOR UPDATE');
        pending=restore(); pending.catch(()=>{}); await waitForLocationLock();
        await blocker.query("UPDATE tickets SET rejoin_deadline_at=clock_timestamp()-interval '1 second'");
        await blocker.query('COMMIT');
        assert.equal((await pending).ticket.servicePriorityBand,'normal');
      } finally {await blocker.query('ROLLBACK'); blocker.release(); if(pending) await pending.catch(()=>{});}
      await reset(); await skipped();
      const revoke=await pool.connect(); pending=undefined;
      try {
        await revoke.query('BEGIN'); await revoke.query('SELECT id FROM store_locations WHERE id=10 FOR UPDATE');
        pending=restore(); pending.catch(()=>{}); await waitForLocationLock();
        await revoke.query('UPDATE tenant_memberships SET is_active=FALSE WHERE user_id=1'); await revoke.query('COMMIT');
        await assert.rejects(pending); assert.equal((await readTicket('1')).status,'skipped');
      } finally {await revoke.query('ROLLBACK'); revoke.release(); if(pending) await pending.catch(()=>{});}
    });
    await t.test('restoration event and webhook failures roll back priority, timestamps, protection and revision',async () => {
      for(const failure of ['event','webhook']) {
        await reset(); await skipped('1',{booking:true});
        const before=(await pool.query('SELECT to_jsonb(t) AS row FROM tickets t')).rows[0].row;
        const revision=(await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision;
        failEvent=failure==='event'; failWebhook=failure==='webhook';
        await assert.rejects(restore(),new RegExp(`${failure} failed`));
        assert.deepEqual((await pool.query('SELECT to_jsonb(t) AS row FROM tickets t')).rows[0].row,before);
        assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,revision);
        assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'protected');
        assert.equal(await count('events'),0); assert.equal(await count('webhooks'),0); assert.equal(pushes,0);
      }
      await reset(); await skipped(); await pool.query("UPDATE store_locations SET queue_lifecycle_mode='enforced' WHERE id=10");
      await assert.rejects(restore(),{code:'QUEUE_DAY_OVERDUE'});
      assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'closed');
      assert.equal(await count('lifecycle_notifications'),1);
      await assert.rejects(restore(),{code:'QUEUE_DAY_UNOPENED'});
      assert.equal(await count('lifecycle_notifications'),1);
    });
    await t.test('vendor walk-ins commit actual ticket, frozen service plan, allowance fixture, event and scope revision without allocation',async () => {
      await reset();
      const results=await Promise.all([walkin(),walkin()]);
      assert.equal(new Set(results.map(r=>r.ticket.sequence)).size,2);
      assert.equal(results.every(r=>r.ticket.status==='waiting' && r.ticket.ticketNumber.startsWith('Q')),true);
      const plans=(await pool.query('SELECT * FROM ticket_service_plans ORDER BY ticket_id')).rows;
      assert.equal(plans.length,2); assert.equal(plans[0].created_by_user_id,'1');
      assert.equal(plans[0].source,'staff_selection'); assert.equal(plans[0].items[0].resource.poolId,'100');
      assert.equal(await count('allowance_audit'),2); assert.equal(await count('events'),2); assert.equal(await count('webhooks'),2); assert.equal(pushes,2);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'3');
      assert.equal(await count('resource_allocations'),0); assert.equal(await count('resource_ledger_commands'),0);
      assert.equal((await pool.query('SELECT count(*)::int AS n FROM tickets WHERE service_started_at IS NOT NULL')).rows[0].n,0);
      await reset(1); await ticket('1',{booking:true}); await record('1','start');
      const before=(await pool.query('SELECT to_jsonb(a) AS row FROM resource_allocations a')).rows[0].row;
      await walkin();
      assert.deepEqual((await pool.query('SELECT to_jsonb(a) AS row FROM resource_allocations a')).rows[0].row,before);
      assert.equal((await pool.query('SELECT state FROM resource_ledger_reservations')).rows[0].state,'converted');
      await reset(4,false); await walkin({serviceId:undefined});
      assert.equal(await count('ticket_service_plans'),0); assert.equal(await count('resource_allocations'),0);
    });
    await t.test('walk-in admission rejects revoked access, inactive scope, paused intake, closed hours and invalid service',async () => {
      for(const sql of [
        "UPDATE tenant_memberships SET is_active=FALSE WHERE user_id=1",
        "UPDATE users SET deletion_requested_at=clock_timestamp() WHERE id=1",
        "UPDATE tenant_memberships SET role='customer' WHERE user_id=1",
        "UPDATE tenant_memberships SET role='staff' WHERE user_id=1",
        "UPDATE store_locations SET is_active=FALSE WHERE id=10",
        "UPDATE tenants SET is_active=FALSE WHERE id=1",
        "UPDATE intake_state SET paused=TRUE",
        "UPDATE store_hours SET is_closed=TRUE",
        "UPDATE vendor_services SET is_active=FALSE",
        "UPDATE location_services SET is_active=FALSE",
        "UPDATE location_services SET location_id=20"
      ]) {
        await reset(); await pool.query(sql); await assert.rejects(walkin());
        assert.equal(await count('tickets'),0); assert.equal(await count('counters'),0); assert.equal(await count('allowance_audit'),0); assert.equal(await count('events'),0);
      }
      await reset();
      await assert.rejects(walkin({actorUserId:undefined}));
      await assert.rejects(walkin({location:{_id:'20'}}));
      await assert.rejects(walkin({serviceId:'9007199254740993'}));
      await assert.rejects(walkin({serviceId:'1x'}));
      await pool.query("UPDATE tenant_memberships SET role='staff' WHERE user_id=1; INSERT INTO tenant_membership_locations VALUES(1,10)");
      assert.equal((await walkin()).ticket.status,'waiting');
    });
    await t.test('walk-ins and restores serialize the final waiting place using current DB threshold',async () => {
      for(const mixed of [false,true]) {
        await reset(); await pool.query('UPDATE tenants SET auto_pause_enabled=TRUE,auto_pause_threshold=1');
        let second=()=>walkin();
        if(mixed) {
          await skipped();
          const dateKey=require('../src/services/queueHelpers').getDateKey(new Date(),'Asia/Manila');
          await pool.query('UPDATE tickets SET date_key=$1',[dateKey]);
          second=()=>restore('1',{queueDateKey:dateKey});
        }
        const results=await Promise.allSettled([walkin(),second()]);
        assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
        assert.match(results.find(r=>r.status==='rejected').reason.code,/QUEUE_(INTAKE|RESTORE)_THRESHOLD_REACHED/);
        assert.equal((await pool.query("SELECT count(*)::int AS n FROM tickets WHERE status='waiting'")).rows[0].n,1);
        assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1);
      }
    });
    await t.test('walk-in event, webhook and allowance failures roll back ticket, sequence, plan, email journey and revision',async () => {
      for(const failure of ['event','webhook','allowance']) {
        await reset(); failEvent=failure==='event'; failWebhook=failure==='webhook'; failAllowance=failure==='allowance';
        await assert.rejects(walkin({customerEmail:'walkin@example.com',notifyByEmail:true}),new RegExp(`${failure} failed`));
        for(const table of ['tickets','counters','ticket_service_plans','allowance_audit','queue_email_journeys','queue_email_slots','events','webhooks','resource_ledger_scopes']) assert.equal(await count(table),0,table);
        assert.equal(pushes,0);
      }
      await reset(); await walkin({customerEmail:'walkin@example.com',notifyByEmail:true});
      assert.equal(await count('queue_email_journeys'),1); assert.equal(await count('queue_email_slots'),10); assert.equal(await count('allowance_audit'),2);
    });
    await t.test('walk-ins reject membership or operating-hours changes committed while waiting for the location lock',async () => {
      for(const sql of ["UPDATE tenant_memberships SET is_active=FALSE WHERE user_id=1","UPDATE store_hours SET is_closed=TRUE"]) {
        await reset();
        const blocker=await pool.connect(); let pending;
        try {
          await blocker.query('BEGIN'); await blocker.query('SELECT id FROM store_locations WHERE id=10 FOR UPDATE');
          pending=walkin(); pending.catch(()=>{}); await waitForLocationLock();
          await blocker.query(sql); await blocker.query('COMMIT');
          await assert.rejects(pending);
          assert.equal(await count('tickets'),0); assert.equal(await count('allowance_audit'),0); assert.equal(await count('events'),0);
        } finally {await blocker.query('ROLLBACK'); blocker.release(); if(pending) await pending.catch(()=>{});}
      }
    });
    await t.test('walk-ins use current enforced Queue Day after lock wait and commit overdue reconciliation before rejecting',async () => {
      await reset();
      const blocker=await pool.connect(); let pending;
      try {
        await blocker.query('BEGIN'); await blocker.query('SELECT id FROM store_locations WHERE id=10 FOR UPDATE');
        pending=walkin(); pending.catch(()=>{}); await waitForLocationLock();
        await blocker.query("UPDATE store_locations SET queue_lifecycle_mode='enforced' WHERE id=10; UPDATE queue_day_state SET closes_at=clock_timestamp()+interval '1 hour'");
        await blocker.query('COMMIT');
        const created=await pending; assert.equal(created.ticket.currentQueueDayId,'999'); assert.equal(created.ticket.dateKey,'20261008');
      } finally {await blocker.query('ROLLBACK'); blocker.release(); if(pending) await pending.catch(()=>{});}
      await reset(); await pool.query("UPDATE store_locations SET queue_lifecycle_mode='enforced' WHERE id=10");
      await assert.rejects(walkin(),{code:'QUEUE_DAY_OVERDUE'});
      assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'closed');
      assert.equal(await count('lifecycle_notifications'),1); assert.equal(await count('tickets'),0);
      await assert.rejects(walkin(),{code:'QUEUE_DAY_UNOPENED'});
      assert.equal(await count('lifecycle_notifications'),1);
    });
    await t.test('expiry between initial open-day and later intake checks commits closure after discarding the requested action',async () => {
      for(const read of [2,3]) {
        await reset(); dueRead=read;
        await ticket('1',{booking:true}); await record('1','start');
        await pool.query("UPDATE store_locations SET queue_lifecycle_mode='enforced' WHERE id=10");
        const revision=(await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision;
        // Controlled Queue Day lookup models the deadline passing between reads.
        // On the third-read case, a transactional fixture writes during admission;
        // savepoint rollback must remove it before closure can commit.
        const raced=loadService({...queueMocks,
          '../repositories/tickets':{...queueMocks['../repositories/tickets'],createTicket:realTickets.createTicket,listWaitingTickets:realTickets.listWaitingTickets},
          './storeHoursService':{assertLocationOpenForCustomerJoin:async (selected,options) => {
            await hours.assertLocationOpenForCustomerJoin(selected,options);
            await options.client.query("INSERT INTO allowance_audit VALUES(99999,'admission-fixture')");
          }}
        },'queueService');
        await assert.rejects(raced.createTicket({tenant,location,actorUserId:'1',joinChannel:'vendor',customerName:'Walk in',serviceId:'1000'}),{code:'QUEUE_DAY_OVERDUE'});
        assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'closed');
        assert.equal(await count('tickets'),1); assert.equal((await readTicket('1')).status,'unserved');
        assert.equal(await count('lifecycle_notifications'),1); assert.equal(await count('allowance_audit'),0); assert.equal(await count('counters'),0);
        assert.equal((await pool.query("SELECT count(*)::int AS n FROM events WHERE event_type='ticket_created'")).rows[0].n,0);
        assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,String(BigInt(revision)+1n));
        assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null);
        const after=(await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision;
        await assert.rejects(walkin(),{code:'QUEUE_DAY_UNOPENED'});
        assert.equal(await count('lifecycle_notifications'),1);
        assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,after);
      }
      await reset(); dueRead=2; failReconciliation=true;
      await pool.query("UPDATE store_locations SET queue_lifecycle_mode='enforced' WHERE id=10");
      await assert.rejects(walkin(),/closure failed/);
      assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'open');
      for(const table of ['tickets','events','lifecycle_notifications','allowance_audit','resource_ledger_scopes']) assert.equal(await count(table),0,table);
    });
    await t.test('bound paid callbacks create one actual ticket, consume one allowance fixture and emit one event/revision after the location lock',async () => {
      await reset(); await payment();
      const results=await Promise.all([paid(),paid()]);
      assert.equal(results.every(r=>r.handled),true);
      assert.equal(await count('tickets'),1); assert.equal(await count('events'),1); assert.equal(await count('webhooks'),1); assert.equal(pushes,1);
      const issued=(await realPayments.findPaymentById('1',{client:pool}));
      assert.equal(issued.ticketIssuanceStatus,'issued'); assert.equal(issued.status,'paid');
      assert.equal((await pool.query('SELECT state FROM payment_allowance')).rows[0].state,'consumed');
      const ticketRow=(await pool.query('SELECT * FROM tickets')).rows[0];
      assert.equal(ticketRow.current_queue_day_id,'999'); assert.equal(ticketRow.status,'waiting'); assert.equal(ticketRow.service_started_at,null);
      assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,'2');
      assert.equal(await count('resource_allocations'),0); assert.equal(await count('resource_ledger_commands'),0);
      assert.equal((await pool.query('SELECT actor_role FROM events')).rows[0].actor_role,null);
    });
    await t.test('bound paid admission blocks unavailable days, scope and subscription without issuing or releasing occupancy',async () => {
      for(const sql of [
        "UPDATE queue_day_state SET intake_mode='paused'",
        "UPDATE queue_day_state SET state='closed'",
        "UPDATE store_locations SET is_active=FALSE WHERE id=10",
        "UPDATE tenants SET is_active=FALSE WHERE id=1",
        "UPDATE store_locations SET queue_lifecycle_mode='legacy' WHERE id=10",
        "UPDATE tenants SET auto_pause_enabled=TRUE,auto_pause_threshold=1 WHERE id=1"
      ]) {
        await reset(); await payment();
        if(sql.includes('threshold')) {await ticket('1'); await pool.query("UPDATE tickets SET status='waiting'");}
        await pool.query(sql); const before=await count('tickets');
        await paid(); assert.equal(await count('tickets'),before);
        const blocked=await realPayments.findPaymentById('1',{client:pool}); assert.equal(blocked.ticketIssuanceStatus,'refund_pending'); assert.equal(blocked.status,'paid');
        assert.equal((await pool.query('SELECT state FROM payment_allowance')).rows[0].state,'released'); assert.equal(pushes,0);
        const revision=(await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision;
        await paid(); assert.equal((await pool.query('SELECT revision::text FROM resource_ledger_scopes')).rows[0].revision,revision);
      }
      await reset(); await payment(); subscriptionUnavailable=true; await paid();
      assert.equal((await realPayments.findPaymentById('1',{client:pool})).ticketIssuanceStatus,'refund_pending'); assert.equal(await count('tickets'),0);
      for(const sql of ["UPDATE users SET deletion_requested_at=clock_timestamp() WHERE id=1","UPDATE users SET platform_access_suspended_at=clock_timestamp() WHERE id=1"]) {
        await reset(); await payment(); await pool.query("UPDATE queue_join_payments SET payload=payload || '{\"userId\":\"1\"}'::jsonb");
        await pool.query(sql); await paid(); assert.equal((await realPayments.findPaymentById('1',{client:pool})).ticketIssuanceStatus,'refund_pending'); assert.equal(await count('tickets'),0);
      }
      await reset(); await ticket('1',{booking:true}); await record('1','start'); await payment();
      await pool.query("UPDATE queue_day_state SET closes_at=clock_timestamp()-interval '1 second'");
      await paid(); assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'closed');
      assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null); assert.equal(await count('tickets'),1);
      assert.equal(await count('lifecycle_notifications'),1); await paid(); assert.equal(await count('lifecycle_notifications'),1);
    });
    await t.test('bound paid ticket, payment link, event and allowance updates roll back on failures',async () => {
      for(const failure of ['event','webhook','allowance','payment']) {
        await reset(); await payment(); failEvent=failure==='event'; failWebhook=failure==='webhook'; failAllowance=failure==='allowance'; failPayment=failure==='payment';
        await assert.rejects(paid(),new RegExp(`${failure} failed`));
        for(const table of ['tickets','events','webhooks','resource_ledger_scopes']) assert.equal(await count(table),0,table);
        assert.equal((await realPayments.findPaymentById('1',{client:pool})).status,'pending'); assert.equal((await pool.query('SELECT state FROM payment_allowance')).rows[0].state,'held'); assert.equal(pushes,0);
      }
      await reset(); await payment(); await pool.query("UPDATE queue_day_state SET closes_at=clock_timestamp()-interval '1 second'"); failReconciliation=true;
      await assert.rejects(paid(),/closure failed/); assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'open');
      assert.equal((await realPayments.findPaymentById('1',{client:pool})).status,'pending'); assert.equal((await pool.query('SELECT state FROM payment_allowance')).rows[0].state,'held');
    });
    await t.test('paid deadline expiry at the later intake check commits blocked payment and closure without a ticket or released occupancy',async () => {
      await reset(); await ticket('1',{booking:true}); await record('1','start'); await payment();
      await pool.query("UPDATE queue_day_state SET closes_at=clock_timestamp()-interval '1 second'"); paidDeadlineRace=true;
      await paid();
      assert.equal((await realPayments.findPaymentById('1',{client:pool})).ticketIssuanceStatus,'refund_pending');
      assert.equal((await pool.query('SELECT state FROM payment_allowance')).rows[0].state,'released');
      assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'closed');
      assert.equal(await count('tickets'),1); assert.equal(await count('lifecycle_notifications'),1);
      assert.equal((await pool.query('SELECT released_at FROM resource_allocations')).rows[0].released_at,null);
      assert.equal((await pool.query("SELECT count(*)::int AS n FROM events WHERE event_type='ticket_created'")).rows[0].n,0);
      await paid(); assert.equal(await count('lifecycle_notifications'),1);
      await reset(); await payment(); await pool.query("UPDATE queue_day_state SET closes_at=clock_timestamp()-interval '1 second'"); failAllowance=true;
      await assert.rejects(paid(),/allowance failed/);
      assert.equal((await pool.query('SELECT state FROM queue_day_state')).rows[0].state,'open');
      assert.equal((await realPayments.findPaymentById('1',{client:pool})).status,'pending');
      assert.equal((await pool.query('SELECT state FROM payment_allowance')).rows[0].state,'held');
      assert.equal(await count('events'),0); assert.equal(await count('lifecycle_notifications'),0);
    });
    await t.test('authenticated paid issuance holds the customer lock through event insertion and records the customer role',async () => {
      await reset(); await payment(); verifyPaidUserLock=true;
      await pool.query("UPDATE queue_join_payments SET payload=payload || '{\"userId\":\"1\"}'::jsonb");
      await paid();
      assert.equal((await pool.query('SELECT actor_role FROM events')).rows[0].actor_role,'customer');
      assert.equal((await pool.query('SELECT user_id::text FROM tickets')).rows[0].user_id,'1');
      await pool.query('SELECT id FROM users WHERE id=1 FOR UPDATE NOWAIT');
    });
    await t.test('paid issuance waits for account deletion or suspension and blocks after their committed update',async () => {
      for(const field of ['deletion_requested_at','platform_access_suspended_at']) {
        await reset(); await payment();
        await pool.query("UPDATE queue_join_payments SET payload=payload || '{\"userId\":\"1\"}'::jsonb");
        const blocker=await pool.connect(); let pending;
        try {
          await blocker.query('BEGIN'); await blocker.query(`UPDATE users SET ${field}=clock_timestamp() WHERE id=1`);
          pending=paid(); pending.catch(()=>{});
          const deadline=Date.now()+3000; let waiting=false;
          while(Date.now()<deadline) {
            waiting=(await pool.query("SELECT 1 FROM pg_stat_activity WHERE application_name=$1 AND wait_event_type='Lock' AND query LIKE 'SELECT id FROM users%'",[schema])).rows.length>0;
            if(waiting) break;
            await new Promise(resolve=>setTimeout(resolve,10));
          }
          assert.equal(waiting,true,'paid admission must wait for the user row');
          await blocker.query('COMMIT'); await pending;
          assert.equal(await count('tickets'),0); assert.equal(await count('events'),0);
          assert.equal((await realPayments.findPaymentById('1',{client:pool})).ticketIssuanceStatus,'refund_pending');
          assert.equal((await pool.query('SELECT state FROM payment_allowance')).rows[0].state,'released');
        } finally {await blocker.query('ROLLBACK'); blocker.release(); if(pending) await pending.catch(()=>{});}
      }
    });
    await t.test('paid admission waits for the location before payment and revalidates provider/day binding',async () => {
      for(const sql of ["UPDATE queue_join_payments SET provider_checkout_session_id='CHANGED' WHERE id=1","UPDATE queue_join_payments SET queue_day_id=998 WHERE id=1"]) {
        await reset(); await payment(); const blocker=await pool.connect(); let pending;
        try {
          await blocker.query('BEGIN'); await blocker.query('SELECT id FROM store_locations WHERE id=10 FOR UPDATE');
          pending=paid(); pending.catch(()=>{}); await waitForLocationLock();
          // This lock must remain available while the callback waits on location.
          await blocker.query('SELECT id FROM queue_join_payments WHERE id=1 FOR UPDATE NOWAIT');
          await blocker.query(sql); await blocker.query('COMMIT'); await assert.rejects(pending,{statusCode:409});
          assert.equal(await count('tickets'),0); assert.equal((await pool.query('SELECT state FROM payment_allowance')).rows[0].state,'held');
        } finally {await blocker.query('ROLLBACK'); blocker.release(); if(pending) await pending.catch(()=>{});}
      }
    });
  } finally {await pool.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`); await pool.end();}
});
