import { Button, Group, Modal, NumberInput, Stack, Text, TextInput, Title } from "@mantine/core";
import type { CreditTask } from "../pages/planControls";
export function CreditTaskModal({ creditTask, busy, setCreditTask, taskUnits, setTaskUnits, providerDisputeId, setProviderDisputeId, taskReason, setTaskReason, runCaseAction }: {
 creditTask: CreditTask | null; busy: boolean; setCreditTask: (task: CreditTask | null) => void;
 taskUnits: number; setTaskUnits: (value: number) => void; providerDisputeId: string; setProviderDisputeId: (value: string) => void;
 taskReason: string; setTaskReason: (value: string) => void; runCaseAction: (task: CreditTask) => Promise<void>;
}) { return (
    <Modal closeButtonProps={{ "aria-label": "Close" }} opened={Boolean(creditTask)} onClose={() => !busy && setCreditTask(null)} closeOnEscape={!busy} closeOnClickOutside={!busy} title={<div className="getprio-modal-title"><Text className="getprio-modal-eyebrow">USAGE CREDIT CONTROL</Text><Title className="getprio-modal-heading" order={3}>{creditTask?.title}</Title></div>} centered size="lg" classNames={{ content: "task-modal", body: "task-modal__body" }}>{creditTask && <div className="task-modal-form"><Stack className="task-modal-form__main"><Text>{creditTask.description}</Text>{creditTask.maxUnits ? <NumberInput min={1} max={creditTask.maxUnits} label={`Units to remove (maximum ${creditTask.maxUnits})`} value={taskUnits} onChange={(value) => setTaskUnits(Number(value) || 0)}/> : null}{creditTask.needsProviderDisputeId ? <TextInput label="Provider dispute ID" value={providerDisputeId} onChange={(event) => setProviderDisputeId(event.target.value)}/> : null}<TextInput label="Reason" description="This reason is stored in the security audit." value={taskReason} onChange={(event) => setTaskReason(event.target.value)}/></Stack><Group className="subscription-editor__footer" justify="space-between"><Text c="dimmed" size="sm">Review the provider evidence and impact before confirming.</Text><Button loading={busy} disabled={taskReason.trim().length < 8 || Boolean(creditTask.maxUnits && (taskUnits < 1 || taskUnits > creditTask.maxUnits)) || Boolean(creditTask.needsProviderDisputeId && !providerDisputeId.trim())} onClick={() => void runCaseAction(creditTask)}>Review and confirm</Button></Group></div>}</Modal>
); }
