// Run against the local fixture dashboard through Playwright CLI's run-code.
export default async function verifySidebarNavigation(page) {
  const origin = new URL(page.url()).origin;
  const help = page.getByRole("button", { name: "Help Center", exact: true });
  const guides = page.locator('[data-sidebar="menu-sub"]').getByText("Guides", { exact: true });
  const expect = (condition, message) => { if (!condition) throw new Error(message); };
  await page.goto(origin);
  await page.getByLabel("Fixture data only, not connected to live Platform data").waitFor();
  await help.waitFor();
  expect(!(await guides.isVisible()), "Submenu must start collapsed outside Help Center");
  await help.click();
  await page.waitForURL(`${origin}/help-center`);
  await guides.waitFor({ state: "visible" });
  expect(await help.getAttribute("aria-expanded") === "true", "Help Center click must expand the menu");
  expect(await guides.isVisible(), "Help Center must reveal its content pages");
  await page.getByRole("button", { name: "Collapse Help Center menu" }).click();
  expect(!(await guides.isVisible()), "Chevron must collapse the submenu");
  expect(page.url() === `${origin}/help-center`, "Collapsing must not navigate");
  await help.click();
  expect(await guides.isVisible(), "Clicking the label must reopen a collapsed menu");
  expect(await page.getByRole("link", { name: "Guides", exact: true }).count() === 1, "Submenu pages must be keyboard-accessible links");
  await page.getByRole("link", { name: "Guides", exact: true }).focus();
  await page.keyboard.press("Enter");
  await page.waitForURL(`${origin}/help-center/guides`);
  expect(await page.locator('[aria-current="page"]').innerText() === "Guides", "Selected guide route must be marked current");
  await page.getByRole("button", { name: "Collapse Help Center menu" }).focus();
  await page.keyboard.press("Enter");
  expect(!(await guides.isVisible()), "Keyboard must collapse the submenu");
  await page.getByRole("button", { name: "Expand Help Center menu" }).focus();
  await page.keyboard.press("Space");
  expect(await guides.isVisible(), "Keyboard must expand the submenu");
  expect(page.url() === `${origin}/help-center/guides`, "Chevron must preserve the selected page");
  await page.getByRole("button", { name: "Collapse Help Center menu" }).click();
  await page.getByRole("button", { name: "Overview", exact: true }).click();
  await page.waitForURL(`${origin}/`);
  await page.goBack();
  await page.waitForURL(`${origin}/help-center/guides`);
  await guides.waitFor({ state: "visible" });
  expect(await help.getAttribute("aria-expanded") === "true", "History navigation must reveal the selected Help Center page");
  await page.goto(`${origin}/help-center/faqs`);
  await help.waitFor();
  expect(await help.getAttribute("aria-expanded") === "true", "Direct FAQ link must expand Help Center");
  expect(await page.locator('[aria-current="page"]').innerText() === "FAQs", "Direct FAQ route must be current");
  await page.goto(origin);
  await help.waitFor();
  await page.getByRole("button", { name: "Toggle Platform navigation" }).click();
  await help.click();
  await page.waitForURL(`${origin}/help-center`);
  await guides.waitFor({ state: "visible" });
  expect(await guides.isVisible(), "Help Center icon must reopen the collapsed desktop sidebar");
  await page.setViewportSize({ width: 834, height: 1112 });
  expect(await guides.isVisible(), "Tablet sidebar must retain expanded navigation");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Toggle Platform navigation" }).click();
  await help.waitFor();
  await page.getByRole("button", { name: "Collapse Help Center menu" }).click();
  await help.click();
  expect(await guides.isVisible(), "Mobile Help Center click must expand its submenu");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), "Mobile page must not overflow horizontally");
  await page.setViewportSize({ width: 1280, height: 900 });
  console.log("Sidebar navigation checks passed (desktop, keyboard, direct links, collapsed sidebar, mobile).");
}
